## Direct Methods for Linear Systems

$$
\begin{align}
        & a_{11}x_1 + \dots + a_{1n}x_n = b_1 \\
        & a_{21}x_1 + \dots + a_{2n}x_n = b_2 \\
        &  \vdots  \\
        & a_{n1}x_1 + \dots + a_{nn}x_n = b_n
\end{align}
$$

We can write this with matrix notation as 

$$
    Ax = b, A \in \mathbb{R}^{n,n}, x,b \in \mathbb{R}^n 
$$


Lets take

$$
\begin{align}
        & x + 3y- 2z = 5 \\
        & 3x + 5y - 6z = 7 \\
        & 2x + 4y + 3z = 8
\end{align}
$$

Becomes

$$
\begin{bmatrix}
1  & 3 & -2 \\
3 & 5 & 6 \\
2 & 4 & 3
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix} = \begin{bmatrix}
5\\
7\\
8
\end{bmatrix}
$$


We could solve it using Gaussian Elimination

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/5f6367f306a7947555dd25f9b3b29a5903efdabb">

Or Cramers Rule

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/39364326c745c93758b2a762e1e25e6e185e2fa7">

<img src ="https://wikimedia.org/api/rest_v1/media/math/render/svg/26cbedff8e480c762c2b0a297f822868151c76ba">

As long as $A$ is non-singular, i.e. 

$$
\text{det}(A) \neq 0 \\
\text{rank}(A) = n \\
Ax = 0 \iff x = 0
$$

We can also solve the system of linear equations using the inverse of $A$ which is defined as $B$ that satisfies 

$$
    AB=BA=I_n
$$

Where $B$ is denominated as $A^{-1}$

Thus 

$$
    x = A^{-1}b = \begin{bmatrix}
-15\\
8\\
2
\end{bmatrix}
$$


## Looking at these concepts in 

<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png">

In [1]:
import numpy as np
import plotly.express as px

## Create Matrix

 Refresher from last module

In [2]:
A = np.array(
    [[1,3,-2],
     [3,5,6],
     [2,4,3]
    ])
A

array([[ 1,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3]])

In [3]:
A.shape

(3, 3)

In [4]:
b = np.array([5,7,8])
b

array([5, 7, 8])

## Solving the system of equations

In [5]:
A_minus = np.linalg.inv(A)
np.dot(A_minus,b)

array([-15.,   8.,   2.])

In [6]:
A_minus @ b

array([-15.,   8.,   2.])

In [7]:
np.linalg.solve(A,b)

array([-15.,   8.,   2.])

## Standard operations act like we would expect

In [8]:
B = np.array(
    [[1,4,9],
     [10,11,12],
     [88,99,111]
    ])

In [9]:
A.T

array([[ 1,  3,  2],
       [ 3,  5,  4],
       [-2,  6,  3]])

In [10]:
A + B

array([[  2,   7,   7],
       [ 13,  16,  18],
       [ 90, 103, 114]])

In [11]:
# Direct product
A*A

array([[ 1,  9,  4],
       [ 9, 25, 36],
       [ 4, 16,  9]])

In [12]:
np.dot(A,A.T)

array([[14,  6,  8],
       [ 6, 70, 44],
       [ 8, 44, 29]])

## Linear algebra operations are in numpy's linalg module

In [13]:
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 9

Determinant of A: -4.000000000000003

Inverse of A:
 [[ 2.25  4.25 -7.  ]
 [-0.75 -1.75  3.  ]
 [-0.5  -0.5   1.  ]]

Matrix A raised to power 3:
 [[ 56 108  78]
 [288 548 414]
 [192 366 275]]


## To apply aggregation functions to n-d arrays we call the function on the array

```python
A.fun()
``` 
The function will take the argument `axis`, which defaults to `none` meaning the entire array will be aggregated to a point

In [25]:
A = np.random.permutation(16).reshape(4,4)
A

array([[ 4,  5, 15,  3],
       [ 7, 12, 14, 13],
       [ 8,  0,  2,  1],
       [11, 10,  9,  6]])

In [26]:
A.sum()

120

In [27]:
A.sum(axis=1)

array([27, 46, 11, 36])

In [28]:
A.sum(axis=0) 

array([30, 27, 40, 23])

## Exercise

Write a function `pdsist(xs)` which returns a matrix of the pairwise distance between the collection of row vectors in `xs` using Euclidean distance.

\begin{align}
    d(x, y) = \sqrt{\sum{(y-x)^2}}
\end{align}


In [19]:
xs = np.array([[0.20981496, 0.54777461, 0.9398527 ],
       [0.63149939, 0.935947  , 0.29834026],
       [0.46302941, 0.25515557, 0.0698739 ],
       [0.38192644, 0.42378508, 0.26055664],
       [0.46307302, 0.05943961, 0.60204931]])

## Simple OLS

In [3]:
n = 200
np.random.seed(seed=1)
# x co-ordinates
x = np.arange(0, n)/100
X = np.array([x, np.ones(n)])
# linearly generated sequence
y = x*10 + np.random.normal(0,3,n)
px.scatter(x=x, y=y, template="none")

We assume that the points follow a linear model
$$
\begin{bmatrix}
y_1  \\
\vdots \\
y_n 
\end{bmatrix}_{nx1} = 
\begin{bmatrix}
1 & X_{11} & X_{21} & \dots & X_{k1}  \\
1 &  X_{12} & X_{22} & \dots & X_{k1} \\
\vdots &  \vdots & \vdots & \vdots & \vdots \\
1 &  X_{1n} & X_{2n} & \dots & X_{kn} \\
\end{bmatrix}_{nxk} \begin{bmatrix}
\beta_1  \\
\vdots \\
\beta_k 
\end{bmatrix}_{kx1}
+
\begin{bmatrix}
\varepsilon_1  \\
\vdots \\
\varepsilon_k 
\end{bmatrix}_{nx1}
$$

$$
    y=X\beta + \varepsilon
$$

$$
\begin{align}
    \varepsilon^T\varepsilon =& \overbrace{(y-X\beta)^T(y-X\beta)}^{||y-X\beta||} \\
            =& y^Ty - \beta^TX^Ty-y^TX+\beta^TX^TX\beta \\
            =& y^Ty - 2\beta^TX^Ty+\beta^TX^TX\beta 
\end{align}
$$

We differentiate with respect to $\beta$ to find $\hat{\beta}$ that minimizes the residuals

$$
\begin{align}
    \dfrac{\partial\varepsilon^T\varepsilon}{\partial\beta} =& -2X^Ty+2\beta^TX^TX\beta =0 \\
  \iff & -X^Ty+2X^TX\beta   = 0  \\
  \iff & (X^TX)\beta   = X^Ty  \\
\end{align}
$$

Multiplying by $(X^TX)^{-1}$ we get an expression for $\hat{\beta}$ 

$$
\begin{align}
    (X^TX)^{-1}(X^TX)\beta   &= (X^TX)^{-1}X^Ty \\
    I \beta &= (X^TX)^{-1}X^Ty
\end{align}
$$

Thus the familiar

$$
\beta = (X^TX)^{-1}X^Ty
$$

## Exercise 

try to implement the simple OLS using the linear algebra we went through.

$$
\beta = (X^TX)^{-1}X^Ty
$$

Valudate your results using

```python
np.linalg.lstsq
```

Create the data using

```python
n = 200
np.random.seed(seed=1)
# x co-ordinates
x = np.arange(0, n)/100
X = np.array([x, np.ones(n)])
# linearly generated sequence
y = x*10 + np.random.normal(0,3,n)
```