## Mini exercise

Create the following array using 3 of the above 5 above.

```
[
 1 1 1 1 1
 1 0 0 0 1
 1 0 0 0 1
 1 0 0 0 1
 1 1 1 1 1
]
``` 
Time: 15 min

Create new (File>New notebook>Python3)
*Random number generation seems less suitable*

In [1]:
import numpy as np
from io import StringIO

data = u"1, 1, 1, 1, 1\n 1, 0, 0, 0, 1\n 1, 0, 0, 0, 1\n 1, 0, 0, 0, 1\n 1, 1, 1, 1, 1"

np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
data = u"11111\n10001\n10001\n10001\n11111"

np.genfromtxt(StringIO(data),delimiter=(1,1,1,1,1))


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
a = [1,1,1,1,1]
b = [1,0,0,0,1]
np.array([a,b,b,b,a])

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [5]:
A=np.concatenate((np.ones(4),np.zeros(21)), axis=0).reshape(5,5)
A
A[::-1].T + A.T[::-1] + A + A.T[::-1].T[::-1]

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
a=np.ones((5,5))
a[1:4,1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Mini exercise

Access the multi-dimensional array `y` to extract the subarray

```
[
    9  10  11
    16 17  18
    23 24  25
]

``` 


In [ ]:
y = np.arange(35).reshape(5,7)
y
y[1:4,2:5]
